"""Import-compatible facade for strict immutable model workflow artifacts."""

from __future__ import annotations

from intelligence.model_workflows.artifact_bundles import (
    _descriptor_files,
    _exact_tree,
    _read_descriptor,
    _read_json,
    artifact_budget,
    verify_comparison_bundle,
    verify_evaluation_bundle,
    verify_train_bundle,
)
from intelligence.model_workflows.artifact_descriptors import (
    COMPARISON_DESCRIPTOR_SCHEMA,
    EVALUATION_DESCRIPTOR_SCHEMA,
    MAX_MODEL_ROWS,
    MISSINGNESS_SCHEMA,
    MODEL_DESCRIPTOR_SCHEMA,
    POPULATION_SCHEMA,
    ArtifactKind,
    ComparisonAcceptanceDescriptor,
    EvaluationAcceptanceDescriptor,
    ModelAcceptanceDescriptor,
    TrainBundle,
    parse_comparison_descriptor,
    parse_evaluation_descriptor,
    parse_model_descriptor,
)
from intelligence.model_workflows.artifact_validation import (
    _population_logical,
    _verify_comparison,
    _verify_evaluation,
    _verify_evaluation_descriptor_files,
    _verify_inventory,
    _verify_missingness,
    _verify_model,
    _verify_population,
    _verify_train_descriptor_files,
)
from intelligence.model_workflows.artifact_writers import (
    _bytes_digest,
    _write_new,
    _write_staged,
    descriptor_value,
    write_json,
    write_ndjson,
    write_staged_json,
    write_staged_ndjson,
)

__all__ = (
    "_bytes_digest",
    "_descriptor_files",
    "_exact_tree",
    "_population_logical",
    "_read_descriptor",
    "_read_json",
    "_verify_comparison",
    "_verify_evaluation",
    "_verify_evaluation_descriptor_files",
    "_verify_inventory",
    "_verify_missingness",
    "_verify_model",
    "_verify_population",
    "_verify_train_descriptor_files",
    "_write_new",
    "_write_staged",
    "ArtifactKind",
    "COMPARISON_DESCRIPTOR_SCHEMA",
    "EVALUATION_DESCRIPTOR_SCHEMA",
    "MAX_MODEL_ROWS",
    "MISSINGNESS_SCHEMA",
    "MODEL_DESCRIPTOR_SCHEMA",
    "POPULATION_SCHEMA",
    "ComparisonAcceptanceDescriptor",
    "EvaluationAcceptanceDescriptor",
    "ModelAcceptanceDescriptor",
    "TrainBundle",
    "artifact_budget",
    "descriptor_value",
    "parse_comparison_descriptor",
    "parse_evaluation_descriptor",
    "parse_model_descriptor",
    "verify_comparison_bundle",
    "verify_evaluation_bundle",
    "verify_train_bundle",
    "write_json",
    "write_ndjson",
    "write_staged_json",
    "write_staged_ndjson",
)
