"""Cypher query constants for the ingestion pipeline.

Every write query is an explicit, parameterized Cypher statement intended to
run inside a single ``session.execute_write`` transaction function. Constants
are organized into thematic submodules for readability and re-exported here
so existing call sites (``from src.graph import queries; queries.X``) keep
working unchanged.
"""

from __future__ import annotations

from src.graph.queries.knows import (
    LINK_PERSON_KNOWS,
    RESOLVE_KNOWS_ENDPOINTS,
    REWIRE_KNOWS_IN,
    REWIRE_KNOWS_OUT,
)
from src.graph.queries.matching import (
    CHECK_IDENTIFIER_FANOUT,
    CHECK_NO_MATCH_LOCK,
    CREATE_MATCH_DECISION,
    CREATE_REVIEW_CASE,
    FIND_CANDIDATES_BY_ADDRESS,
    FIND_CANDIDATES_BY_IDENTIFIER,
    LINK_MATCH_DECISION_LEFT_PERSON,
    LINK_MATCH_DECISION_LEFT_SOURCE_RECORD,
    LINK_MATCH_DECISION_RIGHT_PERSON,
    LINK_MATCH_DECISION_RIGHT_SOURCE_RECORD,
)
from src.graph.queries.merge import (
    CREATE_MERGE_EVENT_AUTO_MERGE,
    CREATE_MERGE_EVENT_PERSON_CREATED,
    CREATE_MERGED_INTO,
    GET_AFFECTED_SOURCE_RECORDS,
    LINK_MERGE_EVENT_AFFECTED_RECORD,
    LINK_MERGE_EVENT_TRIGGERED_BY,
    MARK_PERSON_MERGED,
    PATH_COMPRESS_MERGED_INTO,
    REWIRE_HAS_FACT,
    REWIRE_IDENTIFIED_BY,
    REWIRE_LINKED_TO,
    REWIRE_LIVES_AT,
)
from src.graph.queries.persons import (
    CREATE_ATTRIBUTE_FACT,
    CREATE_PERSON,
    FETCH_PERSON_ADDRESSES,
    FETCH_PERSON_FACTS,
    FETCH_PERSON_IDENTIFIERS,
    LINK_PERSON_TO_ADDRESS,
    LINK_PERSON_TO_IDENTIFIER,
    UPDATE_GOLDEN_PROFILE,
    UPSERT_ADDRESS,
    UPSERT_IDENTIFIER,
)
from src.graph.queries.source_records import (
    CHECK_SOURCE_RECORD_EXISTS,
    CREATE_INGEST_RUN,
    CREATE_SOURCE_RECORD,
    LINK_SOURCE_RECORD_TO_PERSON,
    LINK_SOURCE_RECORD_TO_RUN,
    UPDATE_INGEST_RUN,
)

__all__ = [
    "CHECK_IDENTIFIER_FANOUT",
    "CHECK_NO_MATCH_LOCK",
    "CHECK_SOURCE_RECORD_EXISTS",
    "CREATE_ATTRIBUTE_FACT",
    "CREATE_INGEST_RUN",
    "CREATE_MATCH_DECISION",
    "CREATE_MERGE_EVENT_AUTO_MERGE",
    "CREATE_MERGE_EVENT_PERSON_CREATED",
    "CREATE_MERGED_INTO",
    "CREATE_PERSON",
    "CREATE_REVIEW_CASE",
    "CREATE_SOURCE_RECORD",
    "FETCH_PERSON_ADDRESSES",
    "FETCH_PERSON_FACTS",
    "FETCH_PERSON_IDENTIFIERS",
    "FIND_CANDIDATES_BY_ADDRESS",
    "FIND_CANDIDATES_BY_IDENTIFIER",
    "GET_AFFECTED_SOURCE_RECORDS",
    "LINK_MATCH_DECISION_LEFT_PERSON",
    "LINK_MATCH_DECISION_LEFT_SOURCE_RECORD",
    "LINK_MATCH_DECISION_RIGHT_PERSON",
    "LINK_MATCH_DECISION_RIGHT_SOURCE_RECORD",
    "LINK_MERGE_EVENT_AFFECTED_RECORD",
    "LINK_MERGE_EVENT_TRIGGERED_BY",
    "LINK_PERSON_KNOWS",
    "LINK_PERSON_TO_ADDRESS",
    "LINK_PERSON_TO_IDENTIFIER",
    "LINK_SOURCE_RECORD_TO_PERSON",
    "LINK_SOURCE_RECORD_TO_RUN",
    "MARK_PERSON_MERGED",
    "PATH_COMPRESS_MERGED_INTO",
    "RESOLVE_KNOWS_ENDPOINTS",
    "REWIRE_HAS_FACT",
    "REWIRE_IDENTIFIED_BY",
    "REWIRE_KNOWS_IN",
    "REWIRE_KNOWS_OUT",
    "REWIRE_LINKED_TO",
    "REWIRE_LIVES_AT",
    "UPDATE_GOLDEN_PROFILE",
    "UPDATE_INGEST_RUN",
    "UPSERT_ADDRESS",
    "UPSERT_IDENTIFIER",
]
