from __future__ import annotations

VALIDATE_MAPPING_PROOF_GUARD = (
    "MATCH (release:CrmTenantProjectionRelease {release_id: $release_id, "
    "release_fingerprint: $release_fingerprint})"
    "-[:MATERIALIZES_MAPPING_REVISION]->(revision:CrmTenantMappingRevision {"
    "revision_id: release.mapping_revision_id, revision_number: release.mapping_revision_number, "
    "manifest_digest: release.mapping_manifest_digest, state: $prepared_state, "
    "source_key: release.source_key, source_instance_id: release.source_instance_id, "
    "control_instance_id: release.control_instance_id}) "
    "CALL { WITH revision OPTIONAL MATCH (revision)-[link]->(child) "
    "RETURN count(CASE WHEN link IS NULL THEN NULL "
    "WHEN type(link) = $mapping_entry_link AND child:CrmTenantMappingEntry THEN NULL "
    "ELSE link END) AS bad_revision_links } "
    "CALL { WITH revision OPTIONAL MATCH (revision)-[:HAS_MAPPING_ENTRY]->(entry)-[link]->(child) "
    "RETURN count(CASE WHEN link IS NULL THEN NULL "
    "WHEN type(link) = $mapping_target_link AND child:CrmTenantMappingTarget THEN NULL "
    "ELSE link END) AS bad_entry_links } "
    "CALL { WITH revision OPTIONAL MATCH (revision)-[:HAS_MAPPING_ENTRY]->(:CrmTenantMappingEntry)"
    "-[:HAS_MAPPING_TARGET]->(target)-[link]->(child) "
    "RETURN count(CASE WHEN link IS NULL THEN NULL "
    "WHEN type(link) = $targets_entity_link AND child:Entity THEN NULL "
    "ELSE link END) AS bad_target_links } "
    "CALL { WITH revision MATCH (entry:CrmTenantMappingEntry {revision_id: revision.revision_id}) "
    "OPTIONAL MATCH (owner)-[link:HAS_MAPPING_ENTRY]->(entry) "
    "WITH revision, entry, count(link) AS link_count, count(DISTINCT owner) AS owner_count, "
    "count(DISTINCT CASE WHEN owner = revision THEN owner END) AS revision_owner_count "
    "RETURN count(CASE WHEN link_count = 1 AND owner_count = 1 AND revision_owner_count = 1 "
    "THEN NULL ELSE entry END) AS orphan_entries } "
    "CALL { WITH revision MATCH (entry:CrmTenantMappingEntry {revision_id: revision.revision_id}) "
    "OPTIONAL MATCH (owner)-[link:HAS_MAPPING_ENTRY]->(entry) "
    "WITH revision, entry, count(link) AS link_count, count(DISTINCT owner) AS owner_count, "
    "count(DISTINCT CASE WHEN owner = revision THEN owner END) AS revision_owner_count "
    "RETURN count(CASE WHEN link_count = 1 AND owner_count = 1 AND revision_owner_count = 1 "
    "THEN NULL ELSE entry END) AS bad_entry_owners } "
    "CALL { WITH revision MATCH (entry:CrmTenantMappingEntry {revision_id: revision.revision_id}) "
    "MATCH (target:CrmTenantMappingTarget {entry_id: entry.entry_id}) "
    "OPTIONAL MATCH (owner)-[link:HAS_MAPPING_TARGET]->(target) "
    "WITH entry, target, count(link) AS link_count, count(DISTINCT owner) AS owner_count, "
    "count(DISTINCT CASE WHEN owner = entry THEN owner END) AS entry_owner_count "
    "RETURN count(CASE WHEN link_count = 1 AND owner_count = 1 AND entry_owner_count = 1 "
    "THEN NULL ELSE target END) AS orphan_targets } "
    "CALL { WITH revision MATCH (entry:CrmTenantMappingEntry {revision_id: revision.revision_id}) "
    "MATCH (target:CrmTenantMappingTarget {entry_id: entry.entry_id}) "
    "OPTIONAL MATCH (owner)-[link:HAS_MAPPING_TARGET]->(target) "
    "WITH entry, target, count(link) AS link_count, count(DISTINCT owner) AS owner_count, "
    "count(DISTINCT CASE WHEN owner = entry THEN owner END) AS entry_owner_count "
    "RETURN count(CASE WHEN link_count = 1 AND owner_count = 1 AND entry_owner_count = 1 "
    "THEN NULL ELSE target END) AS bad_target_owners } "
    "CALL { WITH revision MATCH (revision)-[:HAS_MAPPING_ENTRY]->(:CrmTenantMappingEntry)"
    "-[:HAS_MAPPING_TARGET]->(target:CrmTenantMappingTarget) "
    "OPTIONAL MATCH (target)-[link:TARGETS_ENTITY]->(entity:Entity) "
    "WITH target, count(link) AS link_count, count(DISTINCT entity) AS entity_count, "
    "count(DISTINCT CASE WHEN entity.entity_key = target.entity_key THEN entity END) AS matching_count "
    "RETURN count(CASE WHEN link_count = 1 AND entity_count = 1 AND matching_count = 1 "
    "THEN NULL ELSE target END) AS bad_target_entities } "
    "CALL { WITH revision MATCH (entry:CrmTenantMappingEntry {revision_id: revision.revision_id}) "
    "RETURN count(entry) AS entry_count } "
    "CALL { WITH revision MATCH (entry:CrmTenantMappingEntry {revision_id: revision.revision_id}) "
    "MATCH (target:CrmTenantMappingTarget {entry_id: entry.entry_id}) RETURN count(target) AS target_count } "
    "RETURN release.mapping_entry_count AS stored_entry_count, "
    "release.mapping_target_count AS stored_target_count, "
    "release.mapping_topology_fingerprint AS stored_topology_fingerprint, "
    "bad_revision_links, bad_entry_links, bad_target_links, orphan_entries, orphan_targets, "
    "bad_entry_owners, bad_target_owners, bad_target_entities, entry_count, target_count"
)

READ_MAPPING_ENTRY_PROOF_PAGE = (
    "MATCH (:CrmTenantProjectionRelease {release_id: $release_id})"
    "-[:MATERIALIZES_MAPPING_REVISION]->(revision:CrmTenantMappingRevision) "
    "MATCH (revision)-[:HAS_MAPPING_ENTRY]->(entry:CrmTenantMappingEntry) "
    "WHERE $cursor_company_id IS NULL OR toInteger(entry.company_id) > $cursor_company_id "
    "OR (toInteger(entry.company_id) = $cursor_company_id AND entry.entry_id > $cursor_entry_id) "
    "RETURN revision.revision_id AS selected_revision_id, entry.revision_id AS revision_id, "
    "entry.entry_id AS entry_id, entry.company_id AS company_id "
    "ORDER BY toInteger(entry.company_id), entry.entry_id LIMIT $page_limit"
)

READ_MAPPING_TARGET_PROOF_PAGE = (
    "MATCH (:CrmTenantProjectionRelease {release_id: $release_id})"
    "-[:MATERIALIZES_MAPPING_REVISION]->(revision:CrmTenantMappingRevision) "
    "MATCH (revision)-[:HAS_MAPPING_ENTRY]->(entry:CrmTenantMappingEntry)"
    "-[:HAS_MAPPING_TARGET]->(target:CrmTenantMappingTarget) "
    "WHERE $cursor_company_id IS NULL OR toInteger(entry.company_id) > $cursor_company_id "
    "OR (toInteger(entry.company_id) = $cursor_company_id AND target.entity_key > $cursor_entity_key) "
    "OR (toInteger(entry.company_id) = $cursor_company_id AND target.entity_key = $cursor_entity_key "
    "AND target.relationship_kind > $cursor_relationship_kind) "
    "OR (toInteger(entry.company_id) = $cursor_company_id AND target.entity_key = $cursor_entity_key "
    "AND target.relationship_kind = $cursor_relationship_kind AND target.target_id > $cursor_target_id) "
    "RETURN revision.revision_id AS selected_revision_id, entry.revision_id AS revision_id, "
    "entry.entry_id AS entry_id, entry.company_id AS company_id, "
    "target.target_id AS target_id, target.entity_key AS entity_key, "
    "target.relationship_kind AS relationship_kind "
    "ORDER BY toInteger(entry.company_id), target.entity_key, target.relationship_kind, target.target_id "
    "LIMIT $page_limit"
)
