from __future__ import annotations

READ_VALIDATION_RELEASE = (
    "MATCH (release:CrmTenantProjectionRelease {release_id: $release_id}) "
    "RETURN properties(release) AS release"
)

READ_INPUT_PAGE = (
    "MATCH (input:CrmTenantProjectionInput {release_id: $release_id}) "
    "WHERE $cursor_kind IS NULL OR "
    "CASE input.subject_kind WHEN $contact_kind THEN 0 ELSE 1 END > "
    "CASE $cursor_kind WHEN $contact_kind THEN 0 ELSE 1 END OR "
    "(input.subject_kind = $cursor_kind AND toInteger(input.subject_id) > $cursor_subject_id) OR "
    "(input.subject_kind = $cursor_kind AND toInteger(input.subject_id) = $cursor_subject_id "
    "AND input.input_id > $cursor_input_id) "
    "OPTIONAL MATCH (owner:CrmTenantProjectionRelease)-[:HAS_PROJECTION_INPUT]->(input) "
    "OPTIONAL MATCH (input)-[:SELECTS_MEMBERSHIP_SNAPSHOT]->(snapshot) "
    "RETURN properties(input) AS input, properties(snapshot) AS snapshot, count(owner) AS owner_count, "
    "count(snapshot) AS snapshot_count ORDER BY CASE input.subject_kind WHEN $contact_kind THEN 0 ELSE 1 END, "
    "toInteger(input.subject_id), input.input_id LIMIT $page_limit"
)

READ_SNAPSHOT_OBSERVATION_PAGE = (
    "MATCH (release:CrmTenantProjectionRelease {release_id: $release_id})"
    "-[:HAS_PROJECTION_INPUT]->(input:CrmTenantProjectionInput {input_id: $input_id}) "
    "OPTIONAL MATCH (owner:CrmTenantProjectionRelease)-[input_link:HAS_PROJECTION_INPUT]->(input) "
    "WITH release, input, count(input_link) AS input_owner_links, count(DISTINCT owner) AS input_owner_count "
    "OPTIONAL MATCH (input)-[snapshot_link:SELECTS_MEMBERSHIP_SNAPSHOT]->(snapshot:CrmCompanyMembershipSnapshot) "
    "WITH release, input, snapshot, input_owner_links, input_owner_count, count(snapshot_link) AS snapshot_links "
    "OPTIONAL MATCH (snapshot)-[snapshot_link:HAS_MEMBERSHIP_OBSERVATION]->(observation:CrmCompanyMembershipObservation) "
    "WHERE observation IS NULL OR $cursor_observation_id IS NULL "
    "OR observation.observation_id > $cursor_observation_id "
    "OR (observation.observation_id = $cursor_observation_id "
    "AND elementId(observation) > $cursor_node_id) "
    "WITH release, input, snapshot, input_owner_links, input_owner_count, snapshot_links, observation, "
    "count(snapshot_link) AS snapshot_reference_count "
    "OPTIONAL MATCH (:CrmCompanyMembershipSnapshot)-[owner_link:HAS_MEMBERSHIP_OBSERVATION]->(observation) "
    "WITH release, input, snapshot, input_owner_links, input_owner_count, snapshot_links, observation, "
    "snapshot_reference_count, count(owner_link) AS observation_owner_count "
    "OPTIONAL MATCH (observation)-[reference_link:REFERENCES_COMPANY]->(reference:CrmCompanyReference) "
    "WITH release, input, snapshot, input_owner_links, input_owner_count, snapshot_links, observation, "
    "snapshot_reference_count, observation_owner_count, count(reference_link) AS company_reference_count, "
    "min(reference.company_id) AS reference_company_id, min(reference.source_key) AS reference_source_key, "
    "min(reference.source_instance_id) AS reference_source_instance_id, "
    "min(reference.control_instance_id) AS reference_control_instance_id "
    "RETURN properties(input) AS input, properties(snapshot) AS snapshot, input_owner_links, input_owner_count, "
    "snapshot_links, observation.observation_id AS observation_id, elementId(observation) AS observation_node_id, "
    "observation.snapshot_id AS observation_snapshot_id, observation.subject_kind AS observation_subject_kind, "
    "observation.subject_id AS observation_subject_id, observation.company_id AS company_id, "
    "observation.sort AS observation_sort, observation.role_id AS observation_role_id, "
    "observation.is_primary AS observation_is_primary, snapshot_reference_count, observation_owner_count, "
    "company_reference_count, reference_company_id, reference_source_key, reference_source_instance_id, "
    "reference_control_instance_id, snapshot.snapshot_digest AS snapshot_digest, "
    "snapshot.source_record_id AS snapshot_source_record_id, snapshot.source_record_pk AS snapshot_source_record_pk, "
    "snapshot.source_record_version AS snapshot_source_record_version, snapshot.source_record_hash AS snapshot_source_record_hash, "
    "CASE WHEN snapshot.observed_at IS NULL THEN NULL ELSE toString(snapshot.observed_at) END AS snapshot_observed_at, "
    "toString(snapshot.available_at) AS snapshot_available_at, snapshot.contract_version AS snapshot_contract_version, "
    "snapshot.binding_count AS binding_count ORDER BY observation.observation_id, elementId(observation) "
    "LIMIT $page_limit"
)

READ_SNAPSHOT_OBSERVATION_GUARD = (
    "MATCH (release:CrmTenantProjectionRelease {release_id: $release_id})"
    "-[:HAS_PROJECTION_INPUT]->(input:CrmTenantProjectionInput {input_id: $input_id}) "
    "OPTIONAL MATCH (owner:CrmTenantProjectionRelease)-[input_link:HAS_PROJECTION_INPUT]->(input) "
    "WITH input, count(input_link) AS input_owner_links, count(DISTINCT owner) AS input_owner_count "
    "OPTIONAL MATCH (input)-[snapshot_link:SELECTS_MEMBERSHIP_SNAPSHOT]"
    "->(snapshot:CrmCompanyMembershipSnapshot) "
    "WITH input, snapshot, input_owner_links, input_owner_count, count(snapshot_link) AS snapshot_links "
    "OPTIONAL MATCH (snapshot)-[observation_link:HAS_MEMBERSHIP_OBSERVATION]"
    "->(observation:CrmCompanyMembershipObservation) "
    "RETURN properties(input) AS input, properties(snapshot) AS snapshot, input_owner_links, "
    "input_owner_count, snapshot_links, count(observation_link) AS observation_links, "
    "count(DISTINCT observation) AS observation_nodes, count(observation.observation_id) "
    "AS observation_id_count, count(DISTINCT observation.observation_id) AS distinct_observation_ids"
)

READ_DECISION_PAGE = (
    "MATCH (decision:CrmTenantProjectionDecision {release_id: $release_id}) "
    "WHERE $cursor IS NULL OR decision.input_id > $cursor "
    "OPTIONAL MATCH (input:CrmTenantProjectionInput)-[:HAS_PROJECTION_DECISION]->(decision) "
    "OPTIONAL MATCH (input)-[:SELECTS_MEMBERSHIP_SNAPSHOT]->(snapshot) "
    "OPTIONAL MATCH (input)-[:HAS_PROJECTION_ASSOCIATION]->(association) "
    "RETURN properties(decision) AS decision, properties(input) AS input, properties(snapshot) AS snapshot, "
    "count(DISTINCT input) AS input_owner_count, count(DISTINCT snapshot) AS snapshot_count, "
    "count(DISTINCT association) AS association_count ORDER BY decision.input_id LIMIT $page_limit"
)

READ_ASSOCIATION_PAGE = (
    "MATCH (association:CrmTenantProjectionAssociation {release_id: $release_id}) "
    "WHERE $cursor IS NULL OR association.association_id > $cursor "
    "OPTIONAL MATCH (input:CrmTenantProjectionInput)-[:HAS_PROJECTION_ASSOCIATION]->(association) "
    "OPTIONAL MATCH (association)-[:TARGETS_ENTITY]->(entity:Entity) "
    "OPTIONAL MATCH (association)-[:HAS_PROJECTION_SUPPORT]->(support) "
    "RETURN properties(association) AS association, properties(input) AS input, properties(entity) AS entity, "
    "count(DISTINCT input) AS input_owner_count, count(DISTINCT entity) AS entity_count, "
    "count(DISTINCT support) AS support_count ORDER BY association.association_id LIMIT $page_limit"
)

READ_SUPPORT_PAGE = (
    "MATCH (support:CrmTenantProjectionSupport {release_id: $release_id}) "
    "WHERE $cursor IS NULL OR support.support_id > $cursor "
    "OPTIONAL MATCH (association:CrmTenantProjectionAssociation)-[:HAS_PROJECTION_SUPPORT]->(support) "
    "OPTIONAL MATCH (association)<-[:HAS_PROJECTION_ASSOCIATION]-(input:CrmTenantProjectionInput) "
    "OPTIONAL MATCH (input)-[:SELECTS_MEMBERSHIP_SNAPSHOT]->(snapshot) "
    "OPTIONAL MATCH (support)-[:SUPPORTED_BY_MEMBERSHIP]->(observation) "
    "OPTIONAL MATCH (support)-[:SUPPORTED_BY_MAPPING_TARGET]->(target) "
    "OPTIONAL MATCH (entry:CrmTenantMappingEntry)-[:HAS_MAPPING_TARGET]->(target) "
    "OPTIONAL MATCH (revision:CrmTenantMappingRevision)-[:HAS_MAPPING_ENTRY]->(entry) "
    "OPTIONAL MATCH (target)-[:TARGETS_ENTITY]->(entity:Entity) "
    "RETURN properties(support) AS support, properties(association) AS association, properties(input) AS input, "
    "properties(snapshot) AS snapshot, properties(observation) AS observation, properties(target) AS target, "
    "properties(entry) AS entry, properties(revision) AS revision, properties(entity) AS entity, "
    "count(DISTINCT association) AS association_owner_count, count(DISTINCT input) AS input_owner_count, "
    "count(DISTINCT snapshot) AS snapshot_count, count(DISTINCT observation) AS observation_count, "
    "count(DISTINCT target) AS target_count, count(DISTINCT entry) AS entry_count, "
    "count(DISTINCT revision) AS revision_count, count(DISTINCT entity) AS entity_count "
    "ORDER BY support.support_id LIMIT $page_limit"
)

READ_RELEASE_GUARDS = (
    "MATCH (release:CrmTenantProjectionRelease {release_id: $release_id}) "
    "CALL { WITH release MATCH (input:CrmTenantProjectionInput {release_id: release.release_id}) "
    "CALL { WITH release, input OPTIONAL MATCH (owner)-[link:HAS_PROJECTION_INPUT]->(input) "
    "RETURN count(link) AS owner_links, count(DISTINCT owner) AS owner_nodes, "
    "count(DISTINCT CASE WHEN owner = release THEN owner END) AS release_owners } "
    "CALL { WITH input OPTIONAL MATCH (input)-[link:SELECTS_MEMBERSHIP_SNAPSHOT]->(snapshot) "
    "RETURN count(link) AS snapshot_links, count(DISTINCT snapshot) AS snapshots } "
    "CALL { WITH input OPTIONAL MATCH (input)-[link:HAS_PROJECTION_DECISION]->(decision) "
    "RETURN count(link) AS decision_links, count(DISTINCT decision) AS decisions } "
    "RETURN count(CASE WHEN owner_links = 1 AND owner_nodes = 1 AND release_owners = 1 "
    "AND snapshot_links = 1 AND snapshots = 1 AND decision_links = 1 AND decisions = 1 "
    "THEN NULL ELSE input END) AS input_integrity } "
    "CALL { WITH release MATCH (decision:CrmTenantProjectionDecision {release_id: release.release_id}) "
    "CALL { WITH decision OPTIONAL MATCH (input)-[link:HAS_PROJECTION_DECISION]->(decision) "
    "RETURN count(link) AS owner_links, count(DISTINCT input) AS owner_nodes } "
    "RETURN count(CASE WHEN owner_links = 1 AND owner_nodes = 1 THEN NULL ELSE decision END) "
    "AS decision_integrity } "
    "CALL { WITH release MATCH (association:CrmTenantProjectionAssociation {release_id: release.release_id}) "
    "CALL { WITH association OPTIONAL MATCH (input)-[link:HAS_PROJECTION_ASSOCIATION]->(association) "
    "RETURN count(link) AS input_links, count(DISTINCT input) AS inputs } "
    "CALL { WITH association OPTIONAL MATCH (association)-[link:TARGETS_ENTITY]->(entity:Entity) "
    "RETURN count(link) AS entity_links, count(DISTINCT entity) AS entities } "
    "CALL { WITH association OPTIONAL MATCH (association)-[link:HAS_PROJECTION_SUPPORT]->(support) "
    "RETURN count(link) AS support_links, count(DISTINCT support) AS supports } "
    "RETURN count(CASE WHEN input_links = 1 AND inputs = 1 AND entity_links = 1 AND entities = 1 "
    "AND support_links > 0 AND supports > 0 THEN NULL ELSE association END) AS association_integrity } "
    "CALL { WITH release MATCH (support:CrmTenantProjectionSupport {release_id: release.release_id}) "
    "CALL { WITH support OPTIONAL MATCH (association)-[link:HAS_PROJECTION_SUPPORT]->(support) "
    "RETURN count(link) AS association_links, count(DISTINCT association) AS associations } "
    "CALL { WITH support OPTIONAL MATCH (support)-[link:SUPPORTED_BY_MEMBERSHIP]->(observation) "
    "RETURN count(link) AS observation_links, count(DISTINCT observation) AS observations } "
    "CALL { WITH support OPTIONAL MATCH (support)-[link:SUPPORTED_BY_MAPPING_TARGET]->(target) "
    "RETURN count(link) AS target_links, count(DISTINCT target) AS targets } "
    "RETURN count(CASE WHEN association_links = 1 AND associations = 1 AND observation_links = 1 "
    "AND observations = 1 AND target_links = 1 AND targets = 1 THEN NULL ELSE support END) "
    "AS support_integrity } "
    "CALL { WITH release OPTIONAL MATCH (input:CrmTenantProjectionInput {release_id: release.release_id}) "
    "RETURN count(DISTINCT input) AS input_count } "
    "CALL { WITH release OPTIONAL MATCH (decision:CrmTenantProjectionDecision {release_id: release.release_id}) "
    "RETURN count(DISTINCT decision) AS decision_count } "
    "CALL { WITH release OPTIONAL MATCH (association:CrmTenantProjectionAssociation {release_id: release.release_id}) "
    "RETURN count(DISTINCT association) AS association_count } "
    "CALL { WITH release OPTIONAL MATCH (support:CrmTenantProjectionSupport {release_id: release.release_id}) "
    "RETURN count(DISTINCT support) AS support_count } "
    "RETURN properties(release) AS release, input_count, decision_count, association_count, support_count, "
    "input_integrity + decision_integrity + "
    "association_integrity + support_integrity AS integrity_count"
)
