from __future__ import annotations

# Published child payloads are locators only.  The runtime revalidates every
# durable parent/publication identity before constructing a source client.
CLAIM_PUBLISHED_CHILD = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "census_kind: 'source_sync', source_key: $source_key, source_instance_id: $source_instance_id, "
    "control_instance_id: $control_instance_id, request_json: $request_json, "
    "authority_revision: $authority_revision, authority_json: $authority_json}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, "
    "status: 'running'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, frozen_upper_id: $frozen_upper_id}) "
    "MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, task_name: $task_name, task_id: $task_id, "
    "payload_digest: $payload_digest, payload_json: $payload_json, payload_version: $payload_version, "
    "queue: $queue, status: 'published'}) "
    "WHERE coalesce(census.cancel_requested, false) = false "
    "AND census.status IN ['running', 'publishing', 'recovering'] "
    "AND datetime() < datetime($occurrence_deadline) AND datetime() < attempt.attempt_deadline "
    "AND coalesce(census.occurrence_calls, 0) < $occurrence_call_limit "
    "AND coalesce(census.occurrence_rows, 0) < $occurrence_row_limit "
    "AND coalesce(attempt.call_count, 0) < $attempt_call_limit "
    "AND coalesce(attempt.row_count, 0) < $attempt_row_limit "
    "AND unit.state IN ['queued', 'running', 'paused'] "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->"
    "(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key "
    "AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id "
    "AND binding.control_instance_id = census.control_instance_id } "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, "
    "stream_kind: $stream_kind}) "
    "WITH census, attempt, unit, publication, checkpoint WHERE checkpoint IS NULL OR "
    "(checkpoint.frozen_upper_id = $frozen_upper_id AND checkpoint.revision_id IS NULL AND "
    "(checkpoint.generation = $generation OR EXISTS { MATCH (:StandaloneCrmCensusContinuation {"
    "census_id: $census_id, prior_generation: checkpoint.generation, next_generation: $generation}) })) "
    "MERGE (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind}) ON CREATE SET fence.token = 0, fence.status = 'retired' "
    "WITH census, attempt, unit, checkpoint, fence WHERE fence.status = 'retired' OR fence.lease_until < datetime() "
    "SET fence.token = fence.token + 1, fence.status = 'active', fence.owner_id = $owner_id, "
    "fence.lease_until = datetime() + duration({seconds: $lease_seconds}), fence.updated_at = datetime(), "
    "unit.state = 'running', unit.updated_at = datetime() "
    "FOREACH (_ IN CASE WHEN checkpoint IS NULL THEN [] ELSE [1] END | "
    "SET checkpoint.generation = $generation, checkpoint.fence_token = fence.token, checkpoint.updated_at = datetime()) "
    "RETURN fence.token AS fence_token, fence.owner_id AS fence_owner_id, "
    "coalesce(checkpoint.last_committed_id, 0) AS last_committed_id, "
    "checkpoint.binding_subject_id AS binding_subject_id, checkpoint.binding_offset AS binding_offset, "
    "coalesce(checkpoint.processed_rows, 0) AS processed_rows, "
    "coalesce(checkpoint.skipped_rows, 0) AS skipped_rows, attempt.attempt_deadline AS attempt_deadline, "
    "census.created_at AS available_at, census.request_json AS request_json"
)

LEASE_HELD_PUBLISHED_CHILD = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "census_kind: 'source_sync', source_key: $source_key, source_instance_id: $source_instance_id, "
    "control_instance_id: $control_instance_id, request_json: $request_json, "
    "authority_revision: $authority_revision, authority_json: $authority_json}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, "
    "status: 'running'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, frozen_upper_id: $frozen_upper_id}) "
    "MATCH (:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, task_name: $task_name, task_id: $task_id, "
    "payload_digest: $payload_digest, payload_json: $payload_json, payload_version: $payload_version, "
    "queue: $queue, status: 'published'}) "
    "MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, status: 'active'}) "
    "WHERE coalesce(census.cancel_requested, false) = false "
    "AND census.status IN ['running', 'publishing', 'recovering'] "
    "AND datetime() < datetime($occurrence_deadline) AND datetime() < attempt.attempt_deadline "
    "AND coalesce(census.occurrence_calls, 0) < $occurrence_call_limit "
    "AND coalesce(census.occurrence_rows, 0) < $occurrence_row_limit "
    "AND coalesce(attempt.call_count, 0) < $attempt_call_limit "
    "AND coalesce(attempt.row_count, 0) < $attempt_row_limit "
    "AND unit.state IN ['queued', 'running', 'paused'] "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->"
    "(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key "
    "AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id "
    "AND binding.control_instance_id = census.control_instance_id } "
    "AND fence.lease_until >= datetime() "
    "RETURN fence.owner_id AS owner_id"
)

# A broker can deliver after the parent marks an exact publication `publishing`
# but before its post-publish confirmation reaches Neo4j.  This probe is
# deliberately read-only and never permits source client construction.
PRECONFIRM_PUBLISHED_CHILD = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "census_kind: 'source_sync', source_key: $source_key, source_instance_id: $source_instance_id, "
    "control_instance_id: $control_instance_id, request_json: $request_json, "
    "authority_revision: $authority_revision, authority_json: $authority_json}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, stream_kind: $stream_kind, "
    "frozen_upper_id: $frozen_upper_id}) "
    "MATCH (:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, stream_kind: $stream_kind, "
    "task_name: $task_name, task_id: $task_id, payload_digest: $payload_digest, payload_json: $payload_json, "
    "payload_version: $payload_version, queue: $queue, status: 'publishing'}) "
    "WHERE coalesce(census.cancel_requested, false) = false AND census.status IN ['publishing', 'running', 'recovering'] "
    "AND datetime() < datetime($occurrence_deadline) AND datetime() < attempt.attempt_deadline "
    "AND unit.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused'] "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id "
    "AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id AND binding.control_instance_id = census.control_instance_id } "
    "RETURN 1 AS pending"
)

# A claimed worker may process more than one bounded row under the same durable
# task/fence.  This refresh does not acquire a fence: it verifies the exact
# already-held publication identity before the next source effect and returns
# only the checkpoint advanced by the preceding atomic writer.
REFRESH_PUBLISHED_CHILD = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "census_kind: 'source_sync', source_key: $source_key, source_instance_id: $source_instance_id, "
    "control_instance_id: $control_instance_id, request_json: $request_json, "
    "authority_revision: $authority_revision, authority_json: $authority_json}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, "
    "status: 'running'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, state: 'running', frozen_upper_id: $frozen_upper_id}) "
    "MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, token: $fence_token, owner_id: $owner_id, status: 'active'}) "
    "MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, task_name: $task_name, task_id: $task_id, "
    "payload_digest: $payload_digest, payload_json: $payload_json, payload_version: $payload_version, "
    "queue: $queue, status: 'published'}) "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, "
    "stream_kind: $stream_kind, generation: $generation, fence_token: $fence_token, "
    "frozen_upper_id: $frozen_upper_id}) "
    "WHERE coalesce(census.cancel_requested, false) = false "
    "AND census.status IN ['running', 'publishing', 'recovering'] "
    "AND fence.lease_until >= datetime() AND datetime() < datetime($occurrence_deadline) "
    "AND datetime() < attempt.attempt_deadline "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->"
    "(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key "
    "AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id "
    "AND binding.control_instance_id = census.control_instance_id } "
    "RETURN fence.token AS fence_token, fence.owner_id AS fence_owner_id, "
    "coalesce(checkpoint.last_committed_id, 0) AS last_committed_id, "
    "checkpoint.binding_subject_id AS binding_subject_id, checkpoint.binding_offset AS binding_offset, "
    "coalesce(checkpoint.processed_rows, 0) AS processed_rows, "
    "coalesce(checkpoint.skipped_rows, 0) AS skipped_rows, attempt.attempt_deadline AS attempt_deadline, "
    "census.created_at AS available_at, census.request_json AS request_json"
)
CREATE_STANDALONE_CRM_CENSUS_CONSTRAINTS: tuple[str, ...] = (
    "CREATE CONSTRAINT standalone_crm_census_id_unique IF NOT EXISTS FOR (n:StandaloneCrmCensus) REQUIRE n.census_id IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_census_occurrence_unique IF NOT EXISTS FOR (n:StandaloneCrmCensus) REQUIRE (n.source_key, n.source_instance_id, n.control_instance_id, n.census_kind, n.occurrence_key) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_attempt_identity_unique IF NOT EXISTS FOR (n:StandaloneCrmCensusAttempt) REQUIRE (n.census_id, n.generation) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_unit_identity_unique IF NOT EXISTS FOR (n:StandaloneCrmCensusUnit) REQUIRE (n.census_id, n.stream_kind) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_call_intent_unique IF NOT EXISTS FOR (n:StandaloneCrmHttpCallReservation) REQUIRE n.intent_id IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_call_sequence_unique IF NOT EXISTS FOR (n:StandaloneCrmHttpCallReservation) REQUIRE (n.census_id, n.call_sequence) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_publication_unique IF NOT EXISTS FOR (n:StandaloneCrmChildPublication) REQUIRE (n.census_id, n.generation, n.stream_kind) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_checkpoint_unique IF NOT EXISTS FOR (n:StandaloneCrmCensusCheckpoint) REQUIRE (n.census_id, n.stream_kind) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_fence_unique IF NOT EXISTS FOR (n:StandaloneCrmCensusFence) REQUIRE (n.census_id, n.generation, n.stream_kind) IS UNIQUE",
    "CREATE CONSTRAINT standalone_crm_active_scope_unique IF NOT EXISTS FOR (n:StandaloneCrmCensusActiveScope) REQUIRE n.scope_key IS UNIQUE",
    "CREATE INDEX standalone_crm_census_active_scope IF NOT EXISTS FOR (n:StandaloneCrmCensus) ON (n.source_key, n.source_instance_id, n.control_instance_id, n.status)",
    "CREATE INDEX standalone_crm_attempt_lease IF NOT EXISTS FOR (n:StandaloneCrmCensusAttempt) ON (n.census_id, n.status, n.lease_until)",
    "CREATE INDEX standalone_crm_unit_status IF NOT EXISTS FOR (n:StandaloneCrmCensusUnit) ON (n.census_id, n.generation, n.state)",
    "CREATE INDEX standalone_crm_publication_status IF NOT EXISTS FOR (n:StandaloneCrmChildPublication) ON (n.census_id, n.generation, n.status)",
)

ADMIT_CENSUS = (
    "MERGE (scope:StandaloneCrmCensusActiveScope {scope_key: $scope_key}) "
    "WITH scope OPTIONAL MATCH (scope)-[:HAS_ACTIVE_CENSUS]->(active:StandaloneCrmCensus) "
    "WITH scope, collect(active) AS active_rows "
    "OPTIONAL MATCH (replay:StandaloneCrmCensus {source_key: $source_key, "
    "source_instance_id: $source_instance_id, control_instance_id: $control_instance_id, "
    "census_kind: $census_kind, occurrence_key: $occurrence_key}) "
    "WITH scope, active_rows, replay WHERE size(active_rows) <= 1 "
    "AND (replay IS NOT NULL OR size(active_rows) = 0) "
    "MERGE (census:StandaloneCrmCensus {source_key: $source_key, source_instance_id: $source_instance_id, "
    "control_instance_id: $control_instance_id, census_kind: $census_kind, occurrence_key: $occurrence_key}) "
    "ON CREATE SET census.census_id = $census_id, census.fingerprint = $fingerprint, census.request_json = $request_json, "
    "census.authority_revision = $authority_revision, census.authority_json = $authority_json, census.status = 'allocated', "
    "census.generation = 0, census.attempt_count = 0, census.occurrence_calls = 0, census.occurrence_rows = 0, "
    "census.created_at = datetime(), census.updated_at = datetime() "
    "WITH scope, census, replay WHERE census.fingerprint = $fingerprint "
    "FOREACH (_ IN CASE WHEN NOT (census.status IN ['completed', 'failed', 'cancelled_with_checkpoint', 'freeze_failed']) "
    "THEN [1] ELSE [] END | MERGE (scope)-[:HAS_ACTIVE_CENSUS]->(census)) "
    "WITH census, replay "
    "WITH census, replay IS NOT NULL AS replayed "
    "RETURN census.census_id AS census_id, census.status AS status, replayed, "
    "census.fingerprint = $fingerprint AS fingerprint_match"
)

CLAIM_ATTEMPT = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id}) "
    "WHERE census.status IN ['allocated', 'paused_with_checkpoint', 'recovering'] "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND coalesce(census.generation, 0) + 1 = $generation "
    "AND coalesce(census.attempt_count, 0) < $max_attempts "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->"
    "(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key "
    "AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id AND binding.control_instance_id = census.control_instance_id } "
    "SET census.generation = $generation, census.status = 'freezing', census.updated_at = datetime() "
    "CREATE (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, "
    "fence_token: $fence_token, task_id: $attempt_task_id, status: 'running', call_count: 0, row_count: 0, "
    "attempt_deadline: CASE WHEN datetime() + duration({seconds: $attempt_runtime_seconds}) < datetime($occurrence_deadline) "
    "THEN datetime() + duration({seconds: $attempt_runtime_seconds}) ELSE datetime($occurrence_deadline) END, "
    "lease_until: datetime() + duration({seconds: $lease_seconds}), "
    "created_at: datetime(), updated_at: datetime()}) "
    "SET census.attempt_count = coalesce(census.attempt_count, 0) + 1 "
    "RETURN attempt.generation AS generation, attempt.fence_token AS fence_token"
)

RESERVE_CALL = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "WHERE coalesce(census.cancel_requested, false) = false AND census.census_kind = 'source_sync' "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->"
    "(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key "
    "AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id AND binding.control_instance_id = census.control_instance_id } "
    "AND census.status IN ['freezing', 'running', 'publishing', 'recovering'] "
    "AND datetime() < datetime($deadline) AND datetime() < attempt.attempt_deadline "
    "AND attempt.lease_until >= datetime() "
    "AND census.occurrence_calls < $occurrence_call_limit "
    "AND coalesce(attempt.call_count, 0) < $attempt_call_limit "
    "AND (($call_kind = 'probe' AND attempt.fence_token = $fence_token AND attempt.task_id = $task_id) OR EXISTS { MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, "
    "generation: $generation, stream_kind: $stream_kind}) MATCH (unit_fence:StandaloneCrmCensusFence {"
    "census_id: $census_id, generation: $generation, stream_kind: $stream_kind, token: $fence_token, "
    "status: 'active'}) MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, "
    "generation: $generation, stream_kind: $stream_kind, task_id: $task_id, status: 'published'}) "
    "WHERE unit.state IN ['running', 'paused'] AND unit_fence.lease_until >= datetime() }) "
    "SET census.call_sequence = coalesce(census.call_sequence, 0) + 1 "
    "WITH census, attempt "
    "CREATE (call:StandaloneCrmHttpCallReservation {intent_id: $intent_id, census_id: $census_id, "
    "generation: $generation, fence_token: $fence_token, call_kind: $call_kind, stream_kind: $stream_kind, "
    "call_sequence: census.call_sequence, retry_ordinal: $retry_ordinal, cursor: $cursor, subject_id: $subject_id, "
    "reserved_deadline: datetime($deadline), effective_deadline: datetime($effective_deadline), "
    "task_id: $task_id, status: 'reserved', created_at: datetime()}) "
    "SET census.occurrence_calls = census.occurrence_calls + 1, attempt.call_count = coalesce(attempt.call_count, 0) + 1 "
    "RETURN call.intent_id AS intent_id, call.call_sequence AS call_sequence"
)

RECORD_CALL_OUTCOME = (
    "MATCH (call:StandaloneCrmHttpCallReservation {intent_id: $intent_id}) "
    "WHERE call.status = 'reserved' AND $status IN ['succeeded', 'failed'] "
    "SET call.status = $status, call.upper_id = $upper_id, call.error_code = $error_code, "
    "call.completed_at = datetime() RETURN call.intent_id AS intent_id"
)

FREEZE_SOURCE_WINDOW = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, status: 'running'}) "
    "WHERE census.window_json IS NULL AND coalesce(census.cancel_requested, false) = false "
    "SET census.window_json = $window_json, census.status = 'frozen', census.updated_at = datetime() "
    "RETURN census.census_id AS census_id"
)

FREEZE_NO_SOURCE_WINDOW = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, status: 'running'}) "
    "WHERE census.window_json IS NULL AND census.census_kind IN ['mapping_prepare', 'mapping_rollback'] "
    "SET census.window_json = $window_json, census.status = 'frozen', census.updated_at = datetime() "
    "RETURN census.census_id AS census_id"
)

GET_CENSUS_STATUS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id}) "
    "OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "RETURN census.census_id AS census_id, census.status AS status, census.generation AS generation, "
    "census.cancel_requested AS cancel_requested, census.window_json AS window_json, "
    "count(attempt) AS attempts"
)

GET_CENSUS_REQUEST = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id}) "
    "OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "WHERE attempt.generation = census.generation "
    "RETURN census.request_json AS request_json, census.generation AS generation, census.status AS status, "
    "census.window_json AS window_json, "
    "coalesce(census.cancel_requested, false) AS cancel_requested, attempt.attempt_deadline AS attempt_deadline"
)

REQUEST_CANCELLATION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id}) "
    "WHERE census.status IN ['allocated', 'freezing', 'frozen', 'publishing', 'running', "
    "'paused_with_checkpoint', 'recovering'] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "SET census.cancel_requested = true, census.cancelled_by = $actor, "
    "census.cancel_reason = $reason, census.status = 'cancel_requested', census.updated_at = datetime() "
    "RETURN census.census_id AS census_id"
)

RESUME_CENSUS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, status: 'paused_with_checkpoint'}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'paused_with_checkpoint'}) "
    "WHERE coalesce(census.cancel_requested, false) = false AND census.generation = $generation "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND datetime() < attempt.attempt_deadline "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "SET census.status = CASE WHEN census.window_json IS NULL THEN 'freezing' ELSE 'recovering' END, "
    "attempt.status = 'running', attempt.lease_until = datetime() + duration({seconds: $lease_seconds}), "
    "attempt.updated_at = datetime(), census.updated_at = datetime() "
    "RETURN census.census_id AS census_id"
)

CREATE_CONTINUATION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "status: 'paused_with_checkpoint', authority_revision: $authority_revision}) "
    "WHERE census.authority_json = $authority_json AND coalesce(census.cancel_requested, false) = false "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND coalesce(census.attempt_count, 0) < $max_attempts "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND census.generation = $generation "
    "AND NOT EXISTS { MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation}) "
    "WHERE unit.state IN ['running', 'paused'] AND NOT EXISTS { "
    "MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: unit.stream_kind, generation: $generation}) "
    "MATCH (:StandaloneCrmCensusFence {census_id: $census_id, stream_kind: unit.stream_kind, generation: $generation, token: checkpoint.fence_token, status: 'active'}) } } "
    "AND NOT EXISTS { MATCH (:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) } "
    "CREATE (continuation:StandaloneCrmCensusContinuation {census_id: $census_id, "
    "prior_generation: $generation, next_generation: $next_generation, created_at: datetime()}) "
    "CREATE (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $next_generation, "
    "fence_token: $next_generation, task_id: $attempt_task_id, status: 'running', call_count: 0, row_count: 0, "
    "attempt_deadline: CASE WHEN datetime() + duration({seconds: $attempt_runtime_seconds}) < datetime($occurrence_deadline) "
    "THEN datetime() + duration({seconds: $attempt_runtime_seconds}) ELSE datetime($occurrence_deadline) END, "
    "lease_until: datetime() + duration({seconds: $lease_seconds}), created_at: datetime(), updated_at: datetime()}) "
    "SET census.generation = $next_generation, census.attempt_count = coalesce(census.attempt_count, 0) + 1, "
    "census.status = 'recovering', census.updated_at = datetime() "
    "WITH census, continuation "
    "OPTIONAL MATCH (prior_attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation}) "
    "FOREACH (_ IN CASE WHEN prior_attempt IS NULL THEN [] ELSE [1] END | "
    "SET prior_attempt.status = 'superseded', prior_attempt.superseded_at = datetime()) "
    "WITH census, continuation "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation}) "
    "WITH census, continuation, collect(publication) AS publications "
    "FOREACH (publication IN [item IN publications WHERE item.status <> 'retired'] | "
    "SET publication.status = 'retired', publication.retired_at = datetime(), publication.superseded_by_generation = $next_generation) "
    "WITH census, continuation "
    "OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, status: 'active'}) "
    "WITH census, continuation, collect(fence) AS fences "
    "FOREACH (fence IN fences | SET fence.status = 'retired', fence.retired_at = datetime()) "
    "WITH census, continuation "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WHERE unit.generation = $generation AND unit.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused'] "
    "FOREACH (_ IN CASE WHEN unit IS NULL THEN [] ELSE [1] END | "
    "SET unit.generation = $next_generation, unit.state = 'pending_publication', unit.updated_at = datetime()) "
    "RETURN continuation.next_generation AS generation"
)

GET_RESUMABLE_UNITS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, status: 'recovering'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, state: 'pending_publication'}) "
    "WHERE coalesce(census.cancel_requested, false) = false AND census.authority_revision = $authority_revision "
    "AND census.authority_json = $authority_json "
    "RETURN unit.stream_kind AS stream_kind, unit.frozen_upper_id AS frozen_upper_id, "
    "unit.revision_id AS revision_id ORDER BY unit.stream_kind"
)

PAUSE_CENSUS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "WHERE census.status IN ['freezing', 'running', 'publishing', 'frozen', 'recovering'] "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "SET census.status = 'paused_with_checkpoint', census.pause_reason = $reason_code, "
    "census.pause_detail = $detail, census.updated_at = datetime() "
    "WITH census OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "FOREACH (_ IN CASE WHEN attempt IS NULL THEN [] ELSE [1] END | "
    "SET attempt.status = 'paused_with_checkpoint', attempt.updated_at = datetime()) "
    "RETURN census.census_id AS census_id"
)

# A child can fail after its exact fence claim but before its first #302/#303
# mutation.  Persist the claimed checkpoint (including the all-zero initial
# checkpoint) and pause its unit in the same authority-checked transaction so
# continuation has a real durable handoff to inherit.
PAUSE_CLAIMED_UNIT = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, stream_kind: $stream_kind, state: 'running', frozen_upper_id: $frozen_upper_id}) "
    "MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, stream_kind: $stream_kind, "
    "token: $fence_token, owner_id: $owner_id, status: 'active'}) "
    "MATCH (:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, stream_kind: $stream_kind, "
    "task_name: $task_name, task_id: $task_id, payload_digest: $payload_digest, status: 'published'}) "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: $stream_kind}) "
    "WITH census, attempt, unit, fence, checkpoint WHERE census.status IN ['running', 'publishing', 'recovering'] "
    "AND coalesce(census.cancel_requested, false) = false AND census.authority_revision = $authority_revision "
    "AND census.authority_json = $authority_json AND fence.lease_until >= datetime() "
    "AND datetime() < datetime($occurrence_deadline) AND datetime() < attempt.attempt_deadline "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id AND binding.control_instance_id = census.control_instance_id } "
    "AND (checkpoint IS NULL OR (checkpoint.generation = $generation AND checkpoint.fence_token = $fence_token "
    "AND checkpoint.frozen_upper_id = $frozen_upper_id AND checkpoint.revision_id IS NULL "
    "AND checkpoint.last_committed_id = $last_committed_id AND checkpoint.processed_rows = $processed_rows "
    "AND checkpoint.skipped_rows = $skipped_rows AND checkpoint.binding_subject_id = $binding_subject_id "
    "AND checkpoint.binding_offset = $binding_offset)) "
    "AND (checkpoint IS NOT NULL OR ($last_committed_id = 0 AND $processed_rows = 0 AND $skipped_rows = 0 "
    "AND $binding_subject_id IS NULL AND $binding_offset IS NULL)) "
    "MERGE (stored:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: $stream_kind}) "
    "SET stored.last_committed_id = $last_committed_id, stored.processed_rows = $processed_rows, "
    "stored.skipped_rows = $skipped_rows, stored.binding_subject_id = $binding_subject_id, "
    "stored.binding_offset = $binding_offset, stored.generation = $generation, stored.fence_token = $fence_token, "
    "stored.frozen_upper_id = $frozen_upper_id, stored.revision_id = null, stored.updated_at = datetime(), "
    "census.status = 'paused_with_checkpoint', census.pause_reason = $reason_code, census.pause_detail = $detail, "
    "census.updated_at = datetime(), attempt.status = 'paused_with_checkpoint', attempt.updated_at = datetime(), "
    "unit.state = 'paused', unit.updated_at = datetime() "
    "RETURN stored.last_committed_id AS last_committed_id"
)

SETTLE_ATTEMPT = (
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, "
    "status: 'running'}) "
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "WHERE coalesce(census.cancel_requested, false) = false AND census.authority_revision = $authority_revision "
    "AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WITH census, attempt, collect(unit) AS units "
    "WHERE all(unit IN units WHERE unit.state IN ['completed', 'failed', 'cancelled', 'no_work']) "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id}) "
    "WITH census, attempt, collect(publication) AS publications "
    "WHERE all(publication IN publications WHERE publication.status = 'retired') "
    "OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id}) "
    "WITH census, attempt, publications, collect(fence) AS fences "
    "WHERE all(fence IN fences WHERE fence.status = 'retired') "
    "AND NOT EXISTS { MATCH (other_attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "WHERE other_attempt.status IN ['running', 'paused_with_checkpoint'] "
    "AND other_attempt.generation <> $generation } "
    "SET attempt.status = 'completed', attempt.updated_at = datetime() "
    "RETURN attempt.generation AS generation"
)

FAIL_FREEZE = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "WHERE census.status IN ['allocated', 'freezing', 'cancel_requested'] AND census.window_json IS NULL "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "FOREACH (_ IN CASE WHEN attempt IS NULL THEN [] ELSE [1] END | "
    "SET attempt.status = 'failed', attempt.failure_reason = $reason_code, attempt.updated_at = datetime()) "
    "SET census.status = 'freeze_failed', census.terminal_reason = $reason_code, census.expected_units = 0, "
    "census.completed_units = 0, census.failed_units = 0, census.cancelled_units = 0, census.no_work_units = 0, "
    "census.processed_rows = 0, census.skipped_rows = 0, census.terminal_at = datetime(), census.updated_at = datetime() "
    "WITH census OPTIONAL MATCH (:StandaloneCrmCensusActiveScope)-[active:HAS_ACTIVE_CENSUS]->(census) "
    "DELETE active RETURN census.census_id AS census_id"
)

CONVERGE_LIMIT_DENIAL = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id}) "
    "WHERE census.status IN ['allocated', 'freezing', 'frozen', 'publishing', 'running', 'paused_with_checkpoint', 'recovering'] "
    "AND census.generation IN [$generation, $generation - 1] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND (($reason_code = 'attempts_exhausted' AND coalesce(census.attempt_count, 0) >= $max_attempts) "
    "OR ($reason_code = 'deadline_exhausted' AND datetime() >= datetime($occurrence_deadline))) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id "
    "AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.source_instance_id = census.source_instance_id AND binding.control_instance_id = census.control_instance_id } "
    "AND NOT EXISTS { MATCH (current_attempt:StandaloneCrmCensusAttempt {census_id: $census_id, status: 'running'}) "
    "WHERE current_attempt.generation = census.generation } "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id}) "
    "WITH census, collect(publication) AS publications "
    "FOREACH (publication IN [item IN publications WHERE item.status <> 'retired'] | "
    "SET publication.status = 'retired', publication.retired_at = datetime(), publication.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id}) "
    "WITH census, collect(fence) AS fences "
    "FOREACH (fence IN [item IN fences WHERE item.status <> 'retired'] | "
    "SET fence.status = 'retired', fence.retired_at = datetime(), fence.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WITH census, collect(unit) AS units "
    "FOREACH (unit IN [item IN units WHERE item.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused']] | "
    "SET unit.state = 'failed', unit.failure_reason = $reason_code, unit.updated_at = datetime()) "
    "WITH census, units OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "WITH census, units, collect(attempt) AS attempts "
    "FOREACH (attempt IN [item IN attempts WHERE item.status IN ['running', 'paused_with_checkpoint']] | "
    "SET attempt.status = 'failed', attempt.failure_reason = $reason_code, attempt.updated_at = datetime()) "
    "WITH census, units OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id}) "
    "WITH census, units, collect(checkpoint) AS checkpoints "
    "SET census.status = 'failed', "
    "census.terminal_reason = $reason_code, census.expected_units = size(units), "
    "census.completed_units = size([unit IN units WHERE unit.state = 'completed']), "
    "census.failed_units = size([unit IN units WHERE unit.state = 'failed']), "
    "census.cancelled_units = size([unit IN units WHERE unit.state = 'cancelled']), "
    "census.no_work_units = size([unit IN units WHERE unit.state = 'no_work']), "
    "census.processed_rows = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.processed_rows, 0)), "
    "census.skipped_rows = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.skipped_rows, 0)), "
    "census.terminal_at = datetime(), census.updated_at = datetime() "
    "WITH census OPTIONAL MATCH (:StandaloneCrmCensusActiveScope)-[active:HAS_ACTIVE_CENSUS]->(census) "
    "DELETE active RETURN census.status AS status"
)

FAIL_AFTER_WINDOW_AUTHORITY = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "WHERE census.window_json IS NOT NULL "
    "AND census.status IN ['frozen', 'publishing', 'running', 'paused_with_checkpoint', 'recovering', 'cancel_requested'] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id}) "
    "WITH census, collect(publication) AS publications "
    "FOREACH (item IN [publication IN publications WHERE publication.status <> 'retired'] | "
    "SET item.status = 'retired', item.retired_at = datetime(), item.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id}) "
    "WITH census, collect(fence) AS fences "
    "FOREACH (item IN [fence IN fences WHERE fence.status <> 'retired'] | "
    "SET item.status = 'retired', item.retired_at = datetime(), item.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WITH census, collect(unit) AS units "
    "FOREACH (item IN [unit IN units WHERE unit.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused']] | "
    "SET item.state = 'failed', item.failure_reason = $reason_code, item.stop_requested = true, item.updated_at = datetime()) "
    "WITH census, units OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "WITH census, units, collect(attempt) AS attempts "
    "FOREACH (item IN [attempt IN attempts WHERE attempt.status IN ['running', 'paused_with_checkpoint']] | "
    "SET item.status = 'failed', item.failure_reason = $reason_code, item.updated_at = datetime()) "
    "WITH census, units "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id}) "
    "WITH census, units, collect(checkpoint) AS checkpoints "
    "SET census.status = 'failed', census.terminal_reason = $reason_code, census.failure_pending_reconciliation = false, "
    "census.expected_units = size(units), census.completed_units = size([unit IN units WHERE unit.state = 'completed']), "
    "census.failed_units = size([unit IN units WHERE unit.state = 'failed']), "
    "census.cancelled_units = size([unit IN units WHERE unit.state = 'cancelled']), "
    "census.no_work_units = size([unit IN units WHERE unit.state = 'no_work']), "
    "census.processed_rows = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.processed_rows, 0)), "
    "census.skipped_rows = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.skipped_rows, 0)), "
    "census.terminal_at = datetime(), census.updated_at = datetime() "
    "WITH census OPTIONAL MATCH (:StandaloneCrmCensusActiveScope)-[active:HAS_ACTIVE_CENSUS]->(census) "
    "DELETE active RETURN census.census_id AS census_id"
)

FREEZE_WINDOW = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, status: 'freezing'}) "
    "WHERE census.window_json IS NULL AND census.generation = $generation "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) WHERE attempt.attempt_deadline > datetime() } "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->"
    "(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key "
    "AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id "
    "AND binding.source_instance_id = census.source_instance_id } "
    "OPTIONAL MATCH (probe:StandaloneCrmHttpCallReservation {census_id: $census_id}) "
    "WHERE probe.generation = $generation AND probe.call_kind = 'probe' "
    "AND probe.status = 'succeeded' AND probe.upper_id IS NOT NULL "
    "WITH census, [probe IN collect(probe) WHERE probe IS NOT NULL | "
    "{stream_kind: probe.stream_kind, upper_id: probe.upper_id}] AS probe_rows "
    "WHERE (($window_kind = 'source' AND size($selected_bounds) = size($selected_kinds) "
    "AND size(probe_rows) = size($selected_kinds) "
    "AND all(item IN $selected_bounds WHERE item.stream_kind IN $selected_kinds AND item.upper_id >= 0) "
    "AND all(kind IN $selected_kinds WHERE size([item IN $selected_bounds WHERE item.stream_kind = kind]) = 1) "
    "AND all(kind IN $selected_kinds WHERE any(probe IN probe_rows WHERE probe.stream_kind = kind)) "
    "AND all(probe IN probe_rows WHERE probe.stream_kind IN $selected_kinds) "
    "AND all(item IN $selected_bounds WHERE any(probe IN probe_rows WHERE probe.stream_kind = item.stream_kind "
    "AND probe.upper_id = item.upper_id))) "
    "OR ($window_kind = 'mapping' AND size($selected_bounds) = 0)) "
    "SET census.window_json = $window_json, census.status = 'frozen', census.updated_at = datetime() "
    "RETURN census.census_id AS census_id"
)

RESERVE_PUBLICATION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "WHERE census.status IN ['frozen', 'publishing'] "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "MERGE (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind}) "
    "ON CREATE SET publication.task_id = $task_id, publication.payload_digest = $payload_digest, "
    "publication.task_name = $task_name, publication.queue = $queue, publication.payload_json = $payload_json, "
    "publication.payload_version = $payload_version, publication.status = 'pending', publication.created_at = datetime() "
    "WITH census, publication WHERE publication.task_id = $task_id "
    "AND publication.payload_digest = $payload_digest AND publication.task_name = $task_name "
    "AND publication.queue = $queue AND publication.payload_json = $payload_json "
    "AND publication.payload_version = $payload_version "
    "SET publication.updated_at = datetime(), census.status = 'publishing' "
    "RETURN publication.status AS status, publication.task_id AS task_id"
)

CONFIRM_PUBLICATION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, task_id: $task_id}) "
    "WHERE publication.status IN ['pending', 'publishing'] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND coalesce(census.cancel_requested, false) = false AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND EXISTS { MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) WHERE attempt.attempt_deadline > datetime() } "
    "SET publication.status = 'published', publication.published_at = datetime(), publication.updated_at = datetime() "
    "WITH census, publication OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind}) "
    "FOREACH (_ IN CASE WHEN unit IS NULL THEN [] ELSE [1] END | "
    "SET unit.state = CASE WHEN unit.state IN ['pending_publication', 'publishing'] THEN 'queued' ELSE unit.state END, "
    "unit.updated_at = datetime()) "
    "WITH census, publication SET census.status = 'running', census.updated_at = datetime() "
    "RETURN publication.task_id AS task_id"
)

MARK_PUBLICATION_PUBLISHING = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: $stream_kind, task_id: $task_id}) "
    "WHERE publication.status IN ['pending', 'publishing'] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND EXISTS { MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) WHERE attempt.attempt_deadline > datetime() } "
    "SET publication.status = 'publishing', publication.publish_attempts = coalesce(publication.publish_attempts, 0) + 1, "
    "publication.updated_at = datetime() "
    "RETURN publication.payload_json AS payload_json, publication.task_name AS task_name, "
    "publication.queue AS queue, publication.payload_digest AS payload_digest"
)

STORE_CHECKPOINT = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, fence_token: $fence_token, status: 'running'}) "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, stream_kind: $stream_kind}) "
    "OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, stream_kind: $stream_kind, token: $fence_token, status: 'active'}) "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: $stream_kind}) "
    "WITH census, attempt, unit, fence, checkpoint, $processed_rows - coalesce(checkpoint.processed_rows, 0) AS row_delta "
    "WITH census, attempt, unit, fence, checkpoint, row_delta, "
    "CASE WHEN attempt IS NOT NULL AND unit IS NOT NULL AND fence IS NOT NULL "
    "AND census.status IN ['running', 'publishing', 'recovering', 'cancel_requested'] "
    "AND (coalesce(census.cancel_requested, false) = false OR $allow_cancel_checkpoint = true) "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND fence.lease_until >= datetime() AND datetime() < datetime($occurrence_deadline) "
    "AND datetime() < attempt.attempt_deadline "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND coalesce(checkpoint.last_committed_id, -1) <= $last_committed_id "
    "AND coalesce(checkpoint.processed_rows, 0) <= $processed_rows "
    "AND coalesce(checkpoint.skipped_rows, 0) <= $skipped_rows "
    "AND (checkpoint IS NULL OR (checkpoint.binding_subject_id IS NULL AND $binding_subject_id IS NULL) "
    "OR (checkpoint.binding_subject_id IS NOT NULL AND $binding_subject_id IS NOT NULL "
    "AND ($binding_subject_id > checkpoint.binding_subject_id OR ($binding_subject_id = checkpoint.binding_subject_id "
    "AND $binding_offset >= checkpoint.binding_offset)))) "
    "AND (checkpoint IS NULL OR checkpoint.frozen_upper_id = unit.frozen_upper_id) "
    "AND (checkpoint IS NULL OR coalesce(checkpoint.revision_id, '') = coalesce(unit.revision_id, '')) "
    "THEN true ELSE false END AS valid "
    "WITH census, attempt, unit, checkpoint, row_delta, valid, "
    "CASE WHEN NOT valid OR row_delta < 0 THEN 'stale_or_conflict' "
    "WHEN coalesce(census.occurrence_rows, 0) + row_delta > $occurrence_row_limit THEN 'occurrence_exhausted' "
    "WHEN coalesce(attempt.row_count, 0) + row_delta > $attempt_row_limit THEN 'attempt_exhausted' "
    "ELSE 'stored' END AS decision "
    "FOREACH (_ IN CASE WHEN decision = 'stored' THEN [1] ELSE [] END | "
    "MERGE (stored:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: $stream_kind}) "
    "SET stored.last_committed_id = $last_committed_id, stored.processed_rows = $processed_rows, stored.skipped_rows = $skipped_rows, "
    "stored.binding_subject_id = $binding_subject_id, stored.binding_offset = $binding_offset, stored.fence_token = $fence_token, "
    "stored.generation = $generation, stored.frozen_upper_id = unit.frozen_upper_id, stored.revision_id = unit.revision_id, stored.updated_at = datetime(), "
    "census.occurrence_rows = coalesce(census.occurrence_rows, 0) + row_delta, attempt.row_count = coalesce(attempt.row_count, 0) + row_delta) "
    "FOREACH (_ IN CASE WHEN decision = 'attempt_exhausted' THEN [1] ELSE [] END | "
    "SET attempt.status = 'paused_with_checkpoint', census.status = 'paused_with_checkpoint', census.pause_reason = 'attempt_budget_exhausted', census.updated_at = datetime()) "
    "FOREACH (_ IN CASE WHEN decision = 'occurrence_exhausted' THEN [1] ELSE [] END | "
    "SET attempt.status = 'failed', attempt.failure_reason = 'occurrence_budget_exhausted', census.status = 'failed', "
    "census.terminal_reason = 'occurrence_budget_exhausted', census.terminal_at = datetime(), census.updated_at = datetime()) "
    "RETURN decision AS decision"
)

CLOSE_CONTACT_BINDING_POSITION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "census_kind: 'source_sync', authority_revision: $authority_revision, authority_json: $authority_json}) "
    "MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, "
    "stream_kind: 'contact', state: 'running', frozen_upper_id: $frozen_upper_id}) "
    "MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, "
    "stream_kind: 'contact', token: $fence_token, owner_id: $owner_id, status: 'active'}) "
    "MATCH (stored:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: 'contact', "
    "last_committed_id: $last_committed_id, binding_subject_id: $contact_id, binding_offset: $binding_count, "
    "generation: $generation, fence_token: $fence_token, frozen_upper_id: $frozen_upper_id}) "
    "WHERE coalesce(census.cancel_requested, false) = false AND fence.lease_until >= datetime() "
    "AND datetime() < attempt.attempt_deadline AND datetime() < datetime($occurrence_deadline) "
    "AND $contact_id > $last_committed_id AND $contact_id <= $frozen_upper_id "
    "AND EXISTS { MATCH (:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation, "
    "stream_kind: 'contact', task_name: $task_name, task_id: $task_id, "
    "payload_digest: $payload_digest, status: 'published'}) } "
    "SET stored.last_committed_id = $contact_id, stored.binding_subject_id = null, stored.binding_offset = null, "
    "stored.updated_at = datetime() RETURN stored.last_committed_id AS last_committed_id"
)

CONVERGE_OCCURRENCE_EXHAUSTION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, status: 'failed'}) "
    "WHERE census.terminal_reason = 'occurrence_budget_exhausted' "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WITH census, collect(unit) AS units "
    "WHERE all(unit IN units WHERE NOT (unit.state IN ['running', 'paused']) OR EXISTS { "
    "MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: unit.stream_kind, generation: $generation}) "
    "WHERE checkpoint.frozen_upper_id = unit.frozen_upper_id "
    "AND coalesce(checkpoint.revision_id, '') = coalesce(unit.revision_id, '') }) "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id}) "
    "WITH census, units, collect(publication) AS publications "
    "FOREACH (publication IN [item IN publications WHERE item.status <> 'retired'] | SET publication.status = 'retired', publication.retired_at = datetime()) "
    "FOREACH (unit IN [item IN units WHERE item.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused']] | SET unit.state = 'failed', unit.failure_reason = 'occurrence_budget_exhausted', unit.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, status: 'active'}) "
    "WITH census, collect(fence) AS fences "
    "FOREACH (item IN fences | SET item.status = 'retired', item.retired_at = datetime(), item.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "WITH census, collect(attempt) AS attempts "
    "FOREACH (item IN [attempt IN attempts WHERE attempt.status IN ['running', 'paused_with_checkpoint']] | SET item.status = 'failed', item.failure_reason = 'occurrence_budget_exhausted', item.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WITH census, collect(unit) AS units "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id}) "
    "WITH census, units, collect(checkpoint) AS checkpoints "
    "SET census.expected_units = size(units), census.completed_units = size([unit IN units WHERE unit.state = 'completed']), "
    "census.failed_units = size([unit IN units WHERE unit.state = 'failed']), census.cancelled_units = size([unit IN units WHERE unit.state = 'cancelled']), "
    "census.no_work_units = size([unit IN units WHERE unit.state = 'no_work']), "
    "census.processed_rows = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.processed_rows, 0)), "
    "census.skipped_rows = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.skipped_rows, 0)) "
    "WITH census OPTIONAL MATCH (:StandaloneCrmCensusActiveScope)-[active:HAS_ACTIVE_CENSUS]->(census) "
    "DELETE active RETURN census.census_id AS census_id"
)

TERMINALIZE_CENSUS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "WHERE census.status IN ['running', 'cancel_requested', 'recovering', 'publishing', 'frozen', 'failed'] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND ($reason_code = 'authority_stale' OR (EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id })) "
    "AND ($terminal_state = 'failed' OR datetime() < datetime($occurrence_deadline)) "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id}) "
    "WITH census, collect(unit) AS units "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id}) "
    "WITH census, units, collect(publication) AS publications "
    "OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id}) "
    "WITH census, units, publications, collect(fence) AS fences "
    "OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id}) "
    "WITH census, units, publications, fences, collect(attempt) AS attempts "
    "OPTIONAL MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id}) "
    "WITH census, units, publications, fences, attempts, collect(checkpoint) AS checkpoints "
    "WITH census, units, publications, fences, "
    "attempts, checkpoints, size($expected_units) AS expected_units, "
    "size([unit IN units WHERE unit.state = 'completed']) AS completed_units, "
    "size([unit IN units WHERE unit.state = 'failed']) AS failed_units, "
    "size([unit IN units WHERE unit.state = 'cancelled']) AS cancelled_units, "
    "size([unit IN units WHERE unit.state = 'no_work']) AS no_work_units, "
    "size([publication IN publications WHERE publication.status IN ['pending', 'publishing']]) AS unresolved_publications, "
    "size([fence IN fences WHERE fence.status <> 'retired']) AS open_fences "
    "WHERE size(units) = expected_units "
    "AND all(expected IN $expected_units WHERE size([unit IN units WHERE unit.stream_kind = expected.stream_kind "
    "AND unit.frozen_upper_id = expected.frozen_upper_id "
    "AND coalesce(unit.revision_id, '') = coalesce(expected.revision_id, '')]) = 1) "
    "AND all(unit IN units WHERE any(expected IN $expected_units WHERE unit.stream_kind = expected.stream_kind "
    "AND unit.frozen_upper_id = expected.frozen_upper_id "
    "AND coalesce(unit.revision_id, '') = coalesce(expected.revision_id, ''))) "
    "AND all(checkpoint IN checkpoints WHERE any(unit IN units WHERE unit.stream_kind = checkpoint.stream_kind "
    "AND checkpoint.generation = unit.generation AND checkpoint.frozen_upper_id = unit.frozen_upper_id "
    "AND coalesce(checkpoint.revision_id, '') = coalesce(unit.revision_id, ''))) "
    "AND all(unit IN units WHERE unit.state <> 'completed' OR EXISTS { "
    "MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: unit.stream_kind, generation: unit.generation}) "
    "WHERE checkpoint.frozen_upper_id = unit.frozen_upper_id "
    "AND coalesce(checkpoint.revision_id, '') = coalesce(unit.revision_id, '') }) "
    "AND all(unit IN units WHERE unit.state <> 'cancelled' OR NOT EXISTS { "
    "MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, stream_kind: unit.stream_kind, generation: unit.generation}) } OR EXISTS { "
    "MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, stream_kind: unit.stream_kind, generation: unit.generation}) "
    "WHERE checkpoint.frozen_upper_id = unit.frozen_upper_id "
    "AND coalesce(checkpoint.revision_id, '') = coalesce(unit.revision_id, '') }) "
    "AND completed_units + failed_units + cancelled_units + no_work_units = expected_units "
    "AND coalesce(census.occurrence_rows, 0) = reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.processed_rows, 0)) "
    "AND unresolved_publications = 0 AND open_fences = 0 "
    "AND (size([attempt IN attempts WHERE attempt.status IN ['running', 'paused_with_checkpoint']]) = 0 "
    "OR (no_work_units = expected_units AND size([attempt IN attempts WHERE attempt.status = 'running' AND attempt.generation = $generation]) = 1 "
    "AND size([attempt IN attempts WHERE attempt.status IN ['running', 'paused_with_checkpoint'] AND attempt.generation <> $generation]) = 0)) "
    "AND (($terminal_state = 'completed' AND failed_units = 0 AND cancelled_units = 0) "
    "OR ($terminal_state = 'failed' AND (failed_units > 0 OR $reason_code IN ['authority_stale', 'budget_exhausted', 'deadline_exhausted', 'attempts_exhausted', 'occurrence_budget_exhausted', 'attempt_budget_exhausted'])) "
    "OR ($terminal_state = 'cancelled_with_checkpoint' AND failed_units = 0 AND completed_units + cancelled_units + no_work_units = expected_units) "
    "OR ($terminal_state = 'freeze_failed' AND expected_units = 0)) "
    "WITH census, attempts, checkpoints, expected_units, completed_units, failed_units, cancelled_units, no_work_units, "
    "reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.processed_rows, 0)) AS processed_rows, "
    "reduce(total = 0, checkpoint IN checkpoints | total + coalesce(checkpoint.skipped_rows, 0)) AS skipped_rows "
    "FOREACH (attempt IN [attempt IN attempts WHERE attempt.status = 'running'] | SET attempt.status = 'completed', attempt.updated_at = datetime()) "
    "SET census.status = $terminal_state, census.terminal_reason = $reason_code, "
    "census.expected_units = expected_units, census.completed_units = completed_units, "
    "census.failed_units = failed_units, census.cancelled_units = cancelled_units, "
    "census.no_work_units = no_work_units, census.processed_rows = processed_rows, "
    "census.skipped_rows = skipped_rows, census.terminal_at = datetime(), census.updated_at = datetime() "
    "WITH census OPTIONAL MATCH (scope:StandaloneCrmCensusActiveScope)-[active:HAS_ACTIVE_CENSUS]->(census) "
    "DELETE active RETURN census.census_id AS census_id"
)

TAKE_OVER_EXPIRED_ATTEMPT = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id}) "
    "MATCH (prior:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $prior_generation, "
    "status: 'running'}) "
    "WHERE prior.lease_until < datetime() AND census.generation = $prior_generation "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND coalesce(census.attempt_count, 0) < $max_attempts "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND census.window_json IS NULL "
    "SET prior.status = 'superseded', prior.superseded_at = datetime(), census.generation = $next_generation, "
    "census.status = CASE WHEN census.window_json IS NULL THEN 'freezing' ELSE 'recovering' END, "
    "census.updated_at = datetime() "
    "CREATE (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $next_generation, "
    "fence_token: $fence_token, task_id: $attempt_task_id, status: 'running', call_count: 0, row_count: 0, "
    "attempt_deadline: CASE WHEN datetime() + duration({seconds: $attempt_runtime_seconds}) < datetime($occurrence_deadline) "
    "THEN datetime() + duration({seconds: $attempt_runtime_seconds}) ELSE datetime($occurrence_deadline) END, "
    "lease_until: datetime() + duration({seconds: $lease_seconds}), created_at: datetime(), updated_at: datetime()}) "
    "SET census.attempt_count = coalesce(census.attempt_count, 0) + 1 "
    "WITH census, attempt OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $prior_generation}) "
    "WITH census, attempt, collect(publication) AS publications "
    "FOREACH (publication IN [item IN publications WHERE item.status <> 'retired'] | "
    "SET publication.status = 'retired', publication.retired_at = datetime(), publication.superseded_by_generation = $next_generation, publication.updated_at = datetime()) "
    "WITH census, attempt OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $prior_generation, status: 'active'}) "
    "WITH census, attempt, collect(fence) AS fences "
    "FOREACH (fence IN fences | SET fence.status = 'retired', fence.retired_at = datetime(), fence.updated_at = datetime()) "
    "WITH census, attempt OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $prior_generation}) "
    "WITH census, attempt, collect(unit) AS units "
    "FOREACH (unit IN [item IN units WHERE item.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused']] | "
    "SET unit.generation = $next_generation, unit.state = 'pending_publication', unit.updated_at = datetime()) "
    "RETURN attempt.generation AS generation, attempt.fence_token AS fence_token"
)

ALLOCATE_UNITS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "status: $census_status}) WHERE $census_status IN ['frozen', 'recovering'] "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "UNWIND $units AS item "
    "MERGE (unit:StandaloneCrmCensusUnit {census_id: $census_id, stream_kind: item.stream_kind}) "
    "ON CREATE SET unit.generation = $generation, unit.state = item.state, "
    "unit.frozen_upper_id = item.frozen_upper_id, unit.revision_id = item.revision_id, "
    "unit.created_at = datetime(), unit.updated_at = datetime() "
    "WITH census, item, unit "
    "WHERE unit.generation = $generation "
    "AND (unit.frozen_upper_id = item.frozen_upper_id OR (unit.frozen_upper_id IS NULL AND item.frozen_upper_id IS NULL)) "
    "AND (unit.revision_id = item.revision_id OR (unit.revision_id IS NULL AND item.revision_id IS NULL)) "
    "WITH census, collect(unit) AS units "
    "SET census.expected_units = size(units), census.status = CASE WHEN size(units) = 0 "
    "THEN 'running' ELSE 'publishing' END, census.updated_at = datetime() "
    "RETURN size(units) AS allocated"
)

ACQUIRE_UNIT_FENCE = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, stream_kind: $stream_kind}) "
    "WHERE census.status IN ['running', 'publishing', 'recovering'] "
    "AND coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND unit.generation = $generation AND unit.state IN ['queued', 'running', 'paused'] "
    "MERGE (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, stream_kind: $stream_kind}) "
    "ON CREATE SET fence.token = 0, fence.status = 'retired' "
    "WITH census, unit, fence WHERE fence.status = 'retired' OR fence.lease_until < datetime() "
    "SET fence.token = fence.token + 1, fence.status = 'active', "
    "fence.owner_id = $owner_id, fence.lease_until = datetime() + duration({seconds: $lease_seconds}), "
    "fence.updated_at = datetime(), unit.state = 'running', unit.updated_at = datetime() "
    "RETURN fence.token AS fence_token"
)

RENEW_UNIT_FENCE = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, stream_kind: $stream_kind, "
    "generation: $generation, token: $fence_token, status: 'active', owner_id: $owner_id}) "
    "WHERE coalesce(census.cancel_requested, false) = false "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND datetime() < datetime($occurrence_deadline) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "SET fence.lease_until = datetime() + duration({seconds: $lease_seconds}), fence.updated_at = datetime() "
    "RETURN fence.token AS fence_token"
)

SETTLE_UNIT = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, stream_kind: $stream_kind, generation: $generation}) "
    "OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, stream_kind: $stream_kind, "
    "generation: $generation, token: $fence_token, status: 'active'}) "
    "WITH census, unit, fence "
    "WHERE ($no_work OR fence IS NOT NULL) AND census.authority_revision = $authority_revision "
    "AND census.authority_json = $authority_json "
    "AND (coalesce(census.cancel_requested, false) = false OR $allow_cancel_settlement = true) "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "SET unit.state = $unit_state, unit.stop_requested = coalesce(census.cancel_requested, false), "
    "unit.updated_at = datetime() "
    "FOREACH (_ IN CASE WHEN fence IS NULL THEN [] ELSE [1] END | "
    "SET fence.status = 'retired', fence.retired_at = datetime(), fence.updated_at = datetime()) "
    "WITH unit OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, "
    "generation: $generation, stream_kind: $stream_kind}) "
    "WITH unit, collect(publication) AS publications "
    "FOREACH (publication IN [item IN publications WHERE $unit_state IN ['completed', 'failed', 'cancelled'] "
    "AND item.status <> 'retired'] | "
    "SET publication.status = 'retired', publication.retired_at = datetime(), publication.updated_at = datetime()) "
    "RETURN unit.stream_kind AS stream_kind"
)

REQUEST_UNIT_STOPS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, cancel_requested: true}) "
    "MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation}) "
    "WHERE unit.state IN ['pending_publication', 'publishing', 'queued', 'running', 'paused'] "
    "AND census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "SET unit.stop_requested = true, unit.updated_at = datetime() "
    "RETURN count(unit) AS requested"
)

SETTLE_CANCELLATION = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation, "
    "cancel_requested: true}) "
    "WHERE census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "OPTIONAL MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation}) "
    "WITH census, collect(publication) AS publications "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation}) "
    "WITH census, publications, collect(unit) AS units "
    "WHERE all(unit IN units WHERE unit IS NULL OR NOT (unit.state IN ['running', 'paused']) "
    "OR EXISTS { MATCH (checkpoint:StandaloneCrmCensusCheckpoint {census_id: $census_id, "
    "stream_kind: unit.stream_kind, generation: $generation}) "
    "MATCH (:StandaloneCrmCensusFence {census_id: $census_id, stream_kind: unit.stream_kind, "
    "generation: $generation, token: checkpoint.fence_token, status: 'active'}) }) "
    "FOREACH (publication IN [publication IN publications WHERE publication.status IN ['pending', 'publishing', 'published']] | "
    "SET publication.status = 'retired', publication.retired_at = datetime(), publication.updated_at = datetime()) "
    "FOREACH (unit IN [unit IN units WHERE unit.state IN ['pending_publication', 'publishing', 'queued']] | "
    "SET unit.state = 'cancelled', unit.stop_requested = true, unit.updated_at = datetime()) "
    "FOREACH (unit IN [unit IN units WHERE unit.state IN ['running', 'paused']] | "
    "SET unit.state = 'cancelled', unit.stop_requested = true, unit.cancelled_at = datetime(), unit.updated_at = datetime()) "
    "WITH census, units "
    "OPTIONAL MATCH (fence:StandaloneCrmCensusFence {census_id: $census_id, generation: $generation, status: 'active'}) "
    "FOREACH (_ IN CASE WHEN fence IS NULL THEN [] ELSE [1] END | "
    "SET fence.status = 'retired', fence.retired_at = datetime(), fence.updated_at = datetime()) "
    "WITH census OPTIONAL MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) "
    "FOREACH (_ IN CASE WHEN attempt IS NULL THEN [] ELSE [1] END | "
    "SET attempt.status = 'completed', attempt.updated_at = datetime()) "
    "RETURN census.census_id AS census_id"
)

REPAIR_PUBLICATIONS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (publication:StandaloneCrmChildPublication {census_id: $census_id, generation: $generation}) "
    "WHERE publication.status IN ['pending', 'publishing'] AND census.authority_revision = $authority_revision "
    "AND census.authority_json = $authority_json AND coalesce(census.cancel_requested, false) = false "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) "
    "WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key "
    "AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "AND EXISTS { MATCH (attempt:StandaloneCrmCensusAttempt {census_id: $census_id, generation: $generation, status: 'running'}) WHERE attempt.attempt_deadline > datetime() } "
    "OPTIONAL MATCH (unit:StandaloneCrmCensusUnit {census_id: $census_id, generation: $generation, stream_kind: publication.stream_kind}) "
    "WITH census, publication, unit "
    "SET publication.status = CASE WHEN unit.state IN ['queued', 'running', 'paused', 'completed', 'failed', 'cancelled'] "
    "THEN 'published' ELSE publication.status END, publication.updated_at = datetime(), "
    "census.status = CASE WHEN coalesce(census.cancel_requested, false) THEN 'cancel_requested' ELSE census.status END "
    "RETURN publication.task_id AS task_id, publication.status AS status, publication.payload_json AS payload_json, "
    "publication.task_name AS task_name, publication.queue AS queue, publication.payload_digest AS payload_digest, "
    "publication.stream_kind AS stream_kind, publication.generation AS generation"
)

CLASSIFY_UNRESOLVED_CALLS = (
    "MATCH (census:StandaloneCrmCensus {census_id: $census_id, generation: $generation}) "
    "MATCH (call:StandaloneCrmHttpCallReservation {census_id: $census_id, generation: $generation, status: 'reserved'}) "
    "WHERE census.authority_revision = $authority_revision AND census.authority_json = $authority_json "
    "AND EXISTS { MATCH (instance:BitrixSourceInstance {status: 'active'})-[:INSTANCE_OF]->(source:SourceSystem {is_active: true}) WHERE instance.source_key = census.source_key AND instance.source_instance_id = census.source_instance_id AND source.source_key = census.source_key } "
    "AND EXISTS { MATCH (binding:BitrixExecutionSourceBinding) WHERE binding.source_key = census.source_key AND binding.control_instance_id = census.control_instance_id AND binding.source_instance_id = census.source_instance_id } "
    "SET call.status = 'unknown', call.error_code = 'reservation_unresolved', call.completed_at = datetime() "
    "RETURN count(call) AS classified"
)
